name: Build-1.19

on:
  push:
    branches: [ "1.19.2" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build
      id: build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: checkLicenses build publish
      env:
        SNAPSHOT: true
        
    - name: Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Player_Sync
        path: |
            build/libs/
